/*
 * MIT License
 * 
 * Copyright (c) 2025 Husty9 
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.est.munchy.data.database.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.est.munchy.domain.model.MunchRecipe
import com.est.munchy.utils.AppConstants

/**
 * Represents a recipe entity stored in the local database.
 *
 * This data class is annotated with `@Entity`, indicating that it corresponds to a table
 * in the Room database. The table name is specified as `AppConstants.RECIPES_TABLE`.
 *
 * @property recipe The [MunchRecipe] object containing the details of the recipe.
 * @property id The primary key for the recipe entity in the database. It's auto-generated,
 *               ensuring each recipe has a unique identifier.
 *
 * @constructor Creates a [RecipeEntity] instance with the given [recipe].
 *
 * @Entity(tableName = AppConstants.RECIPES_TABLE)
 */
@Entity(tableName = AppConstants.RECIPES_TABLE)
data class RecipeEntity(
    val recipe: MunchRecipe
) {
    /**
     * The primary key for this recipe entity.
     *
     * It's automatically generated by Room when a new recipe is inserted into the database.
     *
     * @PrimaryKey(autoGenerate = true)
     */
    @PrimaryKey(autoGenerate = true)
    var id: Int = 0
}