package com.est.munchy.data.database.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.est.munchy.domain.model.MunchRecipe
import com.est.munchy.utils.AppConstants

/**
 * Represents a recipe entity stored in the local database.
 *
 * This data class is annotated with `@Entity`, indicating that it corresponds to a table
 * in the Room database. The table name is specified as `AppConstants.RECIPES_TABLE`.
 *
 * @property recipe The [MunchRecipe] object containing the details of the recipe.
 * @property id The primary key for the recipe entity in the database. It's auto-generated,
 *               ensuring each recipe has a unique identifier.
 *
 * @constructor Creates a [RecipeEntity] instance with the given [recipe].
 *
 * @Entity(tableName = AppConstants.RECIPES_TABLE)
 */
@Entity(tableName = AppConstants.RECIPES_TABLE)
data class RecipeEntity(
    val recipe: MunchRecipe
) {
    /**
     * The primary key for this recipe entity.
     *
     * It's automatically generated by Room when a new recipe is inserted into the database.
     *
     * @PrimaryKey(autoGenerate = true)
     */
    @PrimaryKey(autoGenerate = true)
    var id: Int = 0
}